server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turnosdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: turnosuser
    password: turnospass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    allow-bean-definition-overriding: true

app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"
  auth:
    base-url: "http://localhost:8081"
  catalog:
    base-url: "http://localhost:8082"

security:
  jwt:
    issuer: "auth-service"  # Debe coincidir con el issuer que pone el AuthService
    public-key-url: "http://localhost:8081/auth/keys/public"  # URL que publica tu llave pública

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
